
title: "Colin M. Henry"
author: "Colin"
url: "https://cmhenry.github.io"
description: "Personal website."

plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-sitemap # leave at the end

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      rawname: post
      permalink: /blog/:title

sass:
  style: compressed
